name: Map

services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${POSTGIS_CONTAINER_NAME:-postgis}
    shm_size: "2gb"
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "${POSTGIS_HOST_PORT:-5432}:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 15s



  route_api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ${ROUTE_API_CONTAINER_NAME:-route_api}
    working_dir: /app
    restart: unless-stopped
    depends_on:
      postgis:
        condition: service_healthy
    volumes:
      - ./server:/app
      - route_api_node_modules:/app/node_modules
      # - /home/sammy/.notebooklm/storage_state.json:/app/.notebooklm/storage_state.json:ro
    command: ["bash", "-lc", "npm install && node route-server.js"]
    ports:
      - "${ROUTE_API_HOST_PORT:-3000}:3000"
    environment:
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}

      DECL_DB_HOST: ${DECL_DB_HOST}
      DECL_DB_PORT: ${DECL_DB_PORT}
      DECL_DB_NAME: ${DECL_DB_NAME}
      DECL_DB_USER: ${DECL_DB_USER}
      DECL_DB_PASSWORD: ${DECL_DB_PASSWORD}
      DECL_DB_SSL: ${DECL_DB_SSL}

      PORT: ${PORT:-3000}

      NOTEBOOKLM_MODE: ${NOTEBOOKLM_MODE:-python}
      NOTEBOOKLM_NOTEBOOK_ID: ${NOTEBOOKLM_NOTEBOOK_ID}
      NOTEBOOKLM_SCRIPT_PATH: ${NOTEBOOKLM_SCRIPT_PATH:-/app/ask_notebooklm.py}
      NOTEBOOKLM_STORAGE_PATH: /app/.notebooklm/storage_state.json
      PYTHON_BIN: ${PYTHON_BIN:-/opt/venv/bin/python}
      NOTEBOOKLM_PYTHON_TIMEOUT_SEC: ${NOTEBOOKLM_PYTHON_TIMEOUT_SEC:-120}

  tegola:
    image: gospatial/tegola:latest
    container_name: ${TEGOLA_CONTAINER_NAME:-tegola}
    restart: unless-stopped
    depends_on:
      postgis:
        condition: service_healthy
    ports:
      - "${TEGOLA_HOST_PORT:-8085}:8080"
    volumes:
      - ./tegola:/config:ro
    command: ["serve", "--config", "/config/tegola.toml"]
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: ${WEB_CONTAINER_NAME:-web}
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - route_api
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    command: ["bash", "-lc", "npm install && npm run dev -- --host 0.0.0.0 --port 5175"]
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_USE_RAILMAP_SUBPATH: ${VITE_USE_RAILMAP_SUBPATH}
    ports:
      - "5175:5175"
volumes:
  postgis_data:
  route_api_node_modules:
  web_node_modules: